# Create a new server
- debug: msg="START a10_server.yaml"
- name: Create a new server
  a10_server:
        host: "{{ inventory_hostname }}"
        username: admin
        password: a10
        server: test1
        validate_certs: false
        state: present
        server_ip: 1.1.1.101
        server_ports:
          - port-number: 8080
            protocol: tcp
          - port-number: 443
            protocol: TCP
- debug: msg="STOP a10_server.yaml"
